"""
Pentagonal numbers are generated by the formula, Pn = n*(3*n-1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
"""

# Generate pentagonal numbers
pent = [(n*(3*n-1))/2 for n in range(1, 10000)]
# Make a set for faster inclusion test
pset = set(pent)

print(min([pent[i+diff]-pent[i]
           for diff in range(1, len(pent))
           for i in range(len(pent)-diff)
           if (pent[i] + pent[i+diff]) in pset and (pent[i+diff] - pent[i]) in pset]))
