"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

tri, pent, hexa = set(), set(), set()
n = 1
while True:
    tri.add((n*(n+1))/2)
    pent.add((n*(3*n-1))/2)
    hexa.add(n*(2*n-1))
    # Only check intersection every 1000 iterations
    if (n % 1000) == 0 and len(set(tri).intersection(pent).intersection(hexa)) > 2:
        break
    n += 1

print list(set(tri).intersection(pent).intersection(hexa))[2]
